build:
    os: linux
    arch: x86
    sign_key: private_key.pem
    sign_certificate: sp-client.pem
    remove_non_regular_files: True

publish:
    url: aoscloud.io
    service_uid:
    tls_key: private_key.pem
    tls_certificate: sp-client.pem
    version: "1.2"

configuration:
    state:
        filename: state.dat
        required: False

    cmd: python3 -u vis_client_example.py
    hostname: 'service-hello-world.local'
    workingDir: '/'
    resources:
        - vis
    env:
        - WEBHOOK_SITE=
    layers:
        - 'py-libs-layer'
