build:
    os: linux
    arch: x86
    sign_key: private_key.pem
    sign_certificate: sp-client.pem
    remove_non_regular_files: True

publish:
    url: staging-fusion.westeurope.cloudapp.azure.com
    service_uid: 80306412-4bb2-44ca-b299-d7bf0d0e93b5
    tls_key: private_key.pem
    tls_certificate: sp-client.pem
    version: "1.1"

configuration:
    state:
        filename: state.dat
        required: False

    cmd: python3 vis_client_example.py
    hostname: 'service-hello-world.local'
    workingDir: '/'
    env:
        - WEBHOOK_SITE=https://webhook.site/3ecdbf71-3eb5-4c19-b947-055ea1929ee4
